export const UNIFIED_TRIP_MAP_PREVIEW_TRIP = {
  id: "preview-trip-tokyo",
  userSelection: {
    location: {
      label: "Tokyo, Japan",
    },
  },
};

export const UNIFIED_TRIP_MAP_PREVIEW_PAYLOAD = {
  destination: "Tokyo, Japan",
  activeDayDefault: 1,
  viewport: {
    bounds: {
      north: 35.739,
      south: 35.652,
      east: 139.829,
      west: 139.69,
    },
  },
  stats: {
    stopCount: 5,
    totalDistanceMeters: 11100,
    averageLegDistanceMeters: 2775,
    unresolvedCount: 1,
    algorithmLabel: "dijkstra-fastest",
    categoryCounts: {
      touristSpots: 5,
      hotels: 1,
      restaurants: 1,
      airports: 1,
      railMetroStations: 2,
      busTerminals: 1,
    },
  },
  provenance: {
    primaryProvider: "world_poi_index",
    sources: [
      { provider: "world_poi_index", sourceType: "local-index" },
      { provider: "google-routes-matrix", sourceType: "routing-api" },
    ],
  },
  latencyBreakdownMs: {
    routeMs: 18,
    recommendationMs: 6,
    overlayMs: 4,
    totalMs: 28,
  },
  layers: {
    touristSpots: [],
    hotels: [
      {
        id: "hotel-park-tokyo",
        name: "Park Hotel Tokyo",
        category: "hotel",
        subcategory: "stay",
        address: "Shiodome, Tokyo",
        dayNumbers: [1, 2],
        source: "recommendations",
        confidence: 0.82,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Park+Hotel+Tokyo",
        coordinates: {
          latitude: 35.664,
          longitude: 139.7597,
        },
      },
    ],
    restaurants: [
      {
        id: "restaurant-ichiran-shibuya",
        name: "Ichiran Shibuya",
        category: "restaurant",
        subcategory: "ramen",
        address: "Shibuya, Tokyo",
        dayNumbers: [1],
        source: "recommendations",
        confidence: 0.8,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Ichiran+Shibuya",
        coordinates: {
          latitude: 35.6598,
          longitude: 139.7004,
        },
      },
    ],
    airports: [
      {
        id: "airport-haneda",
        name: "Haneda Airport",
        category: "airport",
        subcategory: "international",
        address: "Ota, Tokyo",
        dayNumbers: [],
        source: "world_poi_index",
        confidence: 0.92,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Haneda+Airport",
        coordinates: {
          latitude: 35.5494,
          longitude: 139.7798,
        },
      },
    ],
    railMetroStations: [
      {
        id: "station-tokyo",
        name: "Tokyo Station",
        category: "rail_station",
        subcategory: "mainline",
        address: "Chiyoda, Tokyo",
        dayNumbers: [],
        source: "world_poi_index",
        confidence: 0.91,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tokyo+Station",
        coordinates: {
          latitude: 35.6812,
          longitude: 139.7671,
        },
      },
      {
        id: "station-shibuya",
        name: "Shibuya Station",
        category: "metro_station",
        subcategory: "metro",
        address: "Shibuya, Tokyo",
        dayNumbers: [],
        source: "world_poi_index",
        confidence: 0.87,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Shibuya+Station",
        coordinates: {
          latitude: 35.658,
          longitude: 139.7016,
        },
      },
    ],
    busTerminals: [
      {
        id: "bus-busta-shinjuku",
        name: "Busta Shinjuku",
        category: "bus_terminal",
        subcategory: "interchange",
        address: "Shinjuku, Tokyo",
        dayNumbers: [],
        source: "world_poi_index",
        confidence: 0.79,
        mapsUrl: "https://www.google.com/maps/search/?api=1&query=Busta+Shinjuku",
        coordinates: {
          latitude: 35.6886,
          longitude: 139.7006,
        },
      },
    ],
  },
  days: [
    {
      dayNumber: 1,
      title: "Tokyo arrival and east-side highlights",
      routeStatus: "ready",
      routeSummary: {
        totalDistanceMeters: 6400,
        totalDurationSeconds: 3200,
        algorithm: "dijkstra-fastest",
      },
      stops: [
        {
          id: "stop-sensoji",
          name: "Senso-ji",
          category: "tourist_spot",
          subcategory: "temple",
          address: "Asakusa, Tokyo",
          source: "itinerary",
          confidence: 1,
          mapsUrl: "https://www.google.com/maps/search/?api=1&query=Senso-ji",
          dayNumbers: [1],
          visitOrder: 1,
          coordinates: {
            latitude: 35.7148,
            longitude: 139.7967,
          },
        },
        {
          id: "stop-skytree",
          name: "Tokyo Skytree",
          category: "tourist_spot",
          subcategory: "landmark",
          address: "Sumida, Tokyo",
          source: "itinerary",
          confidence: 0.99,
          mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tokyo+Skytree",
          dayNumbers: [1],
          visitOrder: 2,
          coordinates: {
            latitude: 35.7101,
            longitude: 139.8107,
          },
        },
        {
          id: "stop-ueno",
          name: "Ueno Park",
          category: "tourist_spot",
          subcategory: "park",
          address: "Taito, Tokyo",
          source: "itinerary",
          confidence: 0.97,
          mapsUrl: "https://www.google.com/maps/search/?api=1&query=Ueno+Park",
          dayNumbers: [1],
          visitOrder: 3,
          coordinates: {
            latitude: 35.7156,
            longitude: 139.7731,
          },
        },
      ],
      segments: [
        {
          fromStopId: "stop-sensoji",
          toStopId: "stop-skytree",
          distanceMeters: 1800,
          durationSeconds: 780,
          label: "1.8 km",
          provider: "google-routes-matrix",
          polyline: [
            { latitude: 35.7148, longitude: 139.7967 },
            { latitude: 35.7124, longitude: 139.8024 },
            { latitude: 35.7101, longitude: 139.8107 },
          ],
        },
        {
          fromStopId: "stop-skytree",
          toStopId: "stop-ueno",
          distanceMeters: 3100,
          durationSeconds: 1320,
          label: "3.1 km",
          provider: "google-routes-matrix",
          polyline: [
            { latitude: 35.7101, longitude: 139.8107 },
            { latitude: 35.7116, longitude: 139.7962 },
            { latitude: 35.7156, longitude: 139.7731 },
          ],
        },
      ],
      alternatives: [
        {
          rank: 1,
          objective: "fastest",
          objectiveLabel: "Fastest",
          algorithm: "dijkstra-fastest",
        },
      ],
      unresolvedStops: [
        {
          id: "stop-hidden-alley",
          name: "Hidden alley coffee stop",
          dayNumber: 1,
        },
      ],
    },
    {
      dayNumber: 2,
      title: "West Tokyo icons and shrine route",
      routeStatus: "ready",
      routeSummary: {
        totalDistanceMeters: 4700,
        totalDurationSeconds: 2500,
        algorithm: "nearest-neighbor-2opt",
      },
      stops: [
        {
          id: "stop-meiji",
          name: "Meiji Shrine",
          category: "tourist_spot",
          subcategory: "shrine",
          address: "Shibuya, Tokyo",
          source: "itinerary",
          confidence: 0.98,
          mapsUrl: "https://www.google.com/maps/search/?api=1&query=Meiji+Shrine",
          dayNumbers: [2],
          visitOrder: 1,
          coordinates: {
            latitude: 35.6764,
            longitude: 139.6993,
          },
        },
        {
          id: "stop-shibuya",
          name: "Shibuya Crossing",
          category: "tourist_spot",
          subcategory: "district",
          address: "Shibuya, Tokyo",
          source: "itinerary",
          confidence: 0.98,
          mapsUrl: "https://www.google.com/maps/search/?api=1&query=Shibuya+Crossing",
          dayNumbers: [2],
          visitOrder: 2,
          coordinates: {
            latitude: 35.6595,
            longitude: 139.7005,
          },
        },
      ],
      segments: [
        {
          fromStopId: "stop-meiji",
          toStopId: "stop-shibuya",
          distanceMeters: 1700,
          durationSeconds: 620,
          label: "1.7 km",
          provider: "estimated-haversine",
          polyline: [
            { latitude: 35.6764, longitude: 139.6993 },
            { latitude: 35.6682, longitude: 139.6997 },
            { latitude: 35.6595, longitude: 139.7005 },
          ],
        },
      ],
      alternatives: [
        {
          rank: 1,
          objective: "best_experience",
          objectiveLabel: "Best Experience",
          algorithm: "nearest-neighbor-2opt",
        },
      ],
      unresolvedStops: [],
    },
  ],
};
