export const WORLD_POI_DATASET_VERSION = "2026.04-starter-global-v1";

export const WORLD_POI_SEED_DATA = [
  {
    destination: "Bali, Indonesia",
    locality: "Bali",
    countryCode: "ID",
    countryName: "Indonesia",
    name: "Uluwatu Temple",
    altNames: ["Pura Luhur Uluwatu"],
    categories: ["temple", "landmark"],
    geoCoordinates: { latitude: -8.8291, longitude: 115.0849 },
    popularityScore: 0.98,
    sourceIds: { osm: "way/278300803", wikidata: "Q7877621" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Bali, Indonesia",
    locality: "Bali",
    countryCode: "ID",
    countryName: "Indonesia",
    name: "Padang Padang Beach",
    altNames: ["Pantai Labuan Sait"],
    categories: ["beach"],
    geoCoordinates: { latitude: -8.8051, longitude: 115.1005 },
    popularityScore: 0.9,
    sourceIds: { osm: "way/357892819", wikidata: "Q124269275" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Bali, Indonesia",
    locality: "Bali",
    countryCode: "ID",
    countryName: "Indonesia",
    name: "Sacred Monkey Forest Sanctuary",
    altNames: ["Ubud Monkey Forest", "Monkey Forest Ubud"],
    categories: ["park", "landmark"],
    geoCoordinates: { latitude: -8.5195, longitude: 115.2582 },
    popularityScore: 0.95,
    sourceIds: { osm: "way/264459038", wikidata: "Q7396483" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Bali, Indonesia",
    locality: "Bali",
    countryCode: "ID",
    countryName: "Indonesia",
    name: "Tegallalang Rice Terrace",
    altNames: ["Tegalalang Rice Terrace"],
    categories: ["viewpoint", "heritage_site"],
    geoCoordinates: { latitude: -8.4312, longitude: 115.2797 },
    popularityScore: 0.89,
    sourceIds: { osm: "way/301670340", wikidata: "Q7694153" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Dubai, United Arab Emirates",
    locality: "Dubai",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    name: "Burj Khalifa",
    categories: ["landmark", "viewpoint"],
    geoCoordinates: { latitude: 25.1972, longitude: 55.2744 },
    popularityScore: 1,
    sourceIds: { osm: "way/27343072", wikidata: "Q612" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Dubai, United Arab Emirates",
    locality: "Dubai",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    name: "Dubai Marina",
    categories: ["waterfront", "neighborhood"],
    geoCoordinates: { latitude: 25.0800, longitude: 55.1400 },
    popularityScore: 0.94,
    sourceIds: { osm: "relation/1267618", wikidata: "Q12243451" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Dubai, United Arab Emirates",
    locality: "Dubai",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    name: "Al Fahidi Historical Neighbourhood",
    altNames: ["Al Bastakiya", "Bastakiya"],
    categories: ["heritage_site", "neighborhood"],
    geoCoordinates: { latitude: 25.2644, longitude: 55.2962 },
    popularityScore: 0.9,
    sourceIds: { osm: "way/146219608", wikidata: "Q4706589" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Dubai, United Arab Emirates",
    locality: "Dubai",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    name: "Palm Jumeirah",
    categories: ["landmark", "waterfront"],
    geoCoordinates: { latitude: 25.1124, longitude: 55.1390 },
    popularityScore: 0.95,
    sourceIds: { osm: "relation/3196780", wikidata: "Q967596" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Tokyo, Japan",
    locality: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    name: "Senso-ji",
    altNames: ["Asakusa Kannon Temple"],
    categories: ["temple", "landmark"],
    geoCoordinates: { latitude: 35.7148, longitude: 139.7967 },
    popularityScore: 0.99,
    sourceIds: { osm: "way/24305594", wikidata: "Q184429" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Tokyo, Japan",
    locality: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    name: "Shibuya Crossing",
    categories: ["landmark", "neighborhood"],
    geoCoordinates: { latitude: 35.6595, longitude: 139.7005 },
    popularityScore: 0.98,
    sourceIds: { osm: "node/2718509410", wikidata: "Q1554445" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Tokyo, Japan",
    locality: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    name: "Meiji Jingu",
    categories: ["temple", "park"],
    geoCoordinates: { latitude: 35.6764, longitude: 139.6993 },
    popularityScore: 0.95,
    sourceIds: { osm: "way/119505357", wikidata: "Q180699" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Tokyo, Japan",
    locality: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    name: "Tokyo Skytree",
    categories: ["landmark", "viewpoint"],
    geoCoordinates: { latitude: 35.7101, longitude: 139.8107 },
    popularityScore: 0.96,
    sourceIds: { osm: "way/64836518", wikidata: "Q172190" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Kyoto, Japan",
    locality: "Kyoto",
    countryCode: "JP",
    countryName: "Japan",
    name: "Fushimi Inari Shrine",
    altNames: ["Fushimi Inari Taisha"],
    categories: ["temple", "landmark"],
    geoCoordinates: { latitude: 34.9671, longitude: 135.7727 },
    popularityScore: 0.99,
    sourceIds: { osm: "way/87485490", wikidata: "Q355970" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Kyoto, Japan",
    locality: "Kyoto",
    countryCode: "JP",
    countryName: "Japan",
    name: "Kiyomizu-dera",
    categories: ["temple", "heritage_site"],
    geoCoordinates: { latitude: 34.9949, longitude: 135.7850 },
    popularityScore: 0.97,
    sourceIds: { osm: "way/450995439", wikidata: "Q42264" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Kyoto, Japan",
    locality: "Kyoto",
    countryCode: "JP",
    countryName: "Japan",
    name: "Arashiyama Bamboo Grove",
    altNames: ["Arashiyama Bamboo Forest"],
    categories: ["park", "viewpoint"],
    geoCoordinates: { latitude: 35.0170, longitude: 135.6713 },
    popularityScore: 0.95,
    sourceIds: { osm: "way/239447554", wikidata: "Q10434766" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Kyoto, Japan",
    locality: "Kyoto",
    countryCode: "JP",
    countryName: "Japan",
    name: "Gion",
    categories: ["cultural_district", "neighborhood"],
    geoCoordinates: { latitude: 35.0037, longitude: 135.7788 },
    popularityScore: 0.92,
    sourceIds: { osm: "relation/6629857", wikidata: "Q1725484" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Paris, France",
    locality: "Paris",
    countryCode: "FR",
    countryName: "France",
    name: "Eiffel Tower",
    categories: ["landmark", "viewpoint"],
    geoCoordinates: { latitude: 48.8584, longitude: 2.2945 },
    popularityScore: 1,
    sourceIds: { osm: "way/5013364", wikidata: "Q243" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Paris, France",
    locality: "Paris",
    countryCode: "FR",
    countryName: "France",
    name: "Louvre Museum",
    categories: ["museum", "heritage_site"],
    geoCoordinates: { latitude: 48.8606, longitude: 2.3376 },
    popularityScore: 0.99,
    sourceIds: { osm: "way/7515426", wikidata: "Q19675" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Paris, France",
    locality: "Paris",
    countryCode: "FR",
    countryName: "France",
    name: "Montmartre",
    categories: ["neighborhood", "viewpoint"],
    geoCoordinates: { latitude: 48.8867, longitude: 2.3431 },
    popularityScore: 0.9,
    sourceIds: { osm: "relation/71525", wikidata: "Q151397" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Paris, France",
    locality: "Paris",
    countryCode: "FR",
    countryName: "France",
    name: "Jardin du Luxembourg",
    altNames: ["Luxembourg Gardens"],
    categories: ["garden", "park"],
    geoCoordinates: { latitude: 48.8462, longitude: 2.3372 },
    popularityScore: 0.88,
    sourceIds: { osm: "way/4259626", wikidata: "Q190568" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rome, Italy",
    locality: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    name: "Colosseum",
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: 41.8902, longitude: 12.4922 },
    popularityScore: 1,
    sourceIds: { osm: "way/4665643", wikidata: "Q10285" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rome, Italy",
    locality: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    name: "Trevi Fountain",
    altNames: ["Fontana di Trevi"],
    categories: ["landmark", "plaza"],
    geoCoordinates: { latitude: 41.9009, longitude: 12.4833 },
    popularityScore: 0.97,
    sourceIds: { osm: "way/5097220", wikidata: "Q213604" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rome, Italy",
    locality: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    name: "Pantheon",
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: 41.8986, longitude: 12.4769 },
    popularityScore: 0.96,
    sourceIds: { osm: "way/163116442", wikidata: "Q993" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rome, Italy",
    locality: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    name: "Villa Borghese Gardens",
    categories: ["garden", "park"],
    geoCoordinates: { latitude: 41.9142, longitude: 12.4922 },
    popularityScore: 0.85,
    sourceIds: { osm: "way/5594927", wikidata: "Q806777" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "London, United Kingdom",
    locality: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    name: "Tower Bridge",
    categories: ["landmark", "bridge"],
    geoCoordinates: { latitude: 51.5055, longitude: -0.0754 },
    popularityScore: 0.96,
    sourceIds: { osm: "way/205480999", wikidata: "Q83047" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "London, United Kingdom",
    locality: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    name: "British Museum",
    categories: ["museum"],
    geoCoordinates: { latitude: 51.5194, longitude: -0.1270 },
    popularityScore: 0.98,
    sourceIds: { osm: "way/14732975", wikidata: "Q6373" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "London, United Kingdom",
    locality: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    name: "Covent Garden",
    categories: ["market", "cultural_district"],
    geoCoordinates: { latitude: 51.5117, longitude: -0.1230 },
    popularityScore: 0.9,
    sourceIds: { osm: "relation/115523", wikidata: "Q1098010" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "London, United Kingdom",
    locality: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    name: "Hyde Park",
    categories: ["park", "garden"],
    geoCoordinates: { latitude: 51.5073, longitude: -0.1657 },
    popularityScore: 0.88,
    sourceIds: { osm: "way/7779878", wikidata: "Q46104" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Singapore, Singapore",
    locality: "Singapore",
    countryCode: "SG",
    countryName: "Singapore",
    name: "Gardens by the Bay",
    categories: ["garden", "landmark"],
    geoCoordinates: { latitude: 1.2816, longitude: 103.8636 },
    popularityScore: 0.98,
    sourceIds: { osm: "way/130225949", wikidata: "Q5523651" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Singapore, Singapore",
    locality: "Singapore",
    countryCode: "SG",
    countryName: "Singapore",
    name: "Marina Bay Sands SkyPark",
    altNames: ["Marina Bay Sands"],
    categories: ["landmark", "viewpoint"],
    geoCoordinates: { latitude: 1.2834, longitude: 103.8607 },
    popularityScore: 0.97,
    sourceIds: { osm: "way/94749866", wikidata: "Q186965" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Singapore, Singapore",
    locality: "Singapore",
    countryCode: "SG",
    countryName: "Singapore",
    name: "Chinatown",
    categories: ["cultural_district", "market"],
    geoCoordinates: { latitude: 1.2831, longitude: 103.8438 },
    popularityScore: 0.9,
    sourceIds: { osm: "relation/1991960", wikidata: "Q862245" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Singapore, Singapore",
    locality: "Singapore",
    countryCode: "SG",
    countryName: "Singapore",
    name: "Merlion Park",
    categories: ["landmark", "waterfront"],
    geoCoordinates: { latitude: 1.2868, longitude: 103.8545 },
    popularityScore: 0.91,
    sourceIds: { osm: "way/298855730", wikidata: "Q6817110" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "New York City, United States",
    locality: "New York City",
    countryCode: "US",
    countryName: "United States",
    name: "Statue of Liberty",
    categories: ["landmark", "monument"],
    geoCoordinates: { latitude: 40.6892, longitude: -74.0445 },
    popularityScore: 1,
    sourceIds: { osm: "way/60821613", wikidata: "Q9202" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "New York City, United States",
    locality: "New York City",
    countryCode: "US",
    countryName: "United States",
    name: "Central Park",
    categories: ["park", "garden"],
    geoCoordinates: { latitude: 40.7829, longitude: -73.9654 },
    popularityScore: 0.99,
    sourceIds: { osm: "way/427818536", wikidata: "Q160409" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "New York City, United States",
    locality: "New York City",
    countryCode: "US",
    countryName: "United States",
    name: "Times Square",
    categories: ["landmark", "neighborhood"],
    geoCoordinates: { latitude: 40.7580, longitude: -73.9855 },
    popularityScore: 0.98,
    sourceIds: { osm: "node/357604583", wikidata: "Q206731" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "New York City, United States",
    locality: "New York City",
    countryCode: "US",
    countryName: "United States",
    name: "Brooklyn Bridge",
    categories: ["bridge", "landmark"],
    geoCoordinates: { latitude: 40.7061, longitude: -73.9969 },
    popularityScore: 0.92,
    sourceIds: { osm: "way/25389850", wikidata: "Q12536" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Sydney, Australia",
    locality: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    name: "Sydney Opera House",
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: -33.8568, longitude: 151.2153 },
    popularityScore: 1,
    sourceIds: { osm: "way/22238143", wikidata: "Q1395" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Sydney, Australia",
    locality: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    name: "Sydney Harbour Bridge",
    categories: ["bridge", "landmark"],
    geoCoordinates: { latitude: -33.8523, longitude: 151.2108 },
    popularityScore: 0.97,
    sourceIds: { osm: "way/23378422", wikidata: "Q77184" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Sydney, Australia",
    locality: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    name: "Bondi Beach",
    categories: ["beach"],
    geoCoordinates: { latitude: -33.8908, longitude: 151.2743 },
    popularityScore: 0.94,
    sourceIds: { osm: "way/25957452", wikidata: "Q862686" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Sydney, Australia",
    locality: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    name: "The Rocks",
    categories: ["heritage_site", "neighborhood"],
    geoCoordinates: { latitude: -33.8599, longitude: 151.2090 },
    popularityScore: 0.88,
    sourceIds: { osm: "relation/390179", wikidata: "Q2279212" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Cairo, Egypt",
    locality: "Cairo",
    countryCode: "EG",
    countryName: "Egypt",
    name: "Great Pyramid of Giza",
    altNames: ["Pyramid of Khufu"],
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: 29.9792, longitude: 31.1342 },
    popularityScore: 1,
    sourceIds: { osm: "way/5016747", wikidata: "Q34636" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Cairo, Egypt",
    locality: "Cairo",
    countryCode: "EG",
    countryName: "Egypt",
    name: "Egyptian Museum",
    categories: ["museum"],
    geoCoordinates: { latitude: 30.0478, longitude: 31.2336 },
    popularityScore: 0.94,
    sourceIds: { osm: "way/101202957", wikidata: "Q230350" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Cairo, Egypt",
    locality: "Cairo",
    countryCode: "EG",
    countryName: "Egypt",
    name: "Khan el-Khalili",
    categories: ["market", "cultural_district"],
    geoCoordinates: { latitude: 30.0478, longitude: 31.2625 },
    popularityScore: 0.89,
    sourceIds: { osm: "way/150880751", wikidata: "Q751574" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Cairo, Egypt",
    locality: "Cairo",
    countryCode: "EG",
    countryName: "Egypt",
    name: "Citadel of Cairo",
    categories: ["fort", "heritage_site"],
    geoCoordinates: { latitude: 30.0299, longitude: 31.2613 },
    popularityScore: 0.87,
    sourceIds: { osm: "way/24859307", wikidata: "Q639711" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rio de Janeiro, Brazil",
    locality: "Rio de Janeiro",
    countryCode: "BR",
    countryName: "Brazil",
    name: "Christ the Redeemer",
    altNames: ["Cristo Redentor"],
    categories: ["landmark", "monument"],
    geoCoordinates: { latitude: -22.9519, longitude: -43.2105 },
    popularityScore: 1,
    sourceIds: { osm: "way/60642624", wikidata: "Q79985" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rio de Janeiro, Brazil",
    locality: "Rio de Janeiro",
    countryCode: "BR",
    countryName: "Brazil",
    name: "Sugarloaf Mountain",
    altNames: ["Pao de Acucar"],
    categories: ["viewpoint", "landmark"],
    geoCoordinates: { latitude: -22.9486, longitude: -43.1566 },
    popularityScore: 0.96,
    sourceIds: { osm: "node/712289410", wikidata: "Q1007962" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rio de Janeiro, Brazil",
    locality: "Rio de Janeiro",
    countryCode: "BR",
    countryName: "Brazil",
    name: "Copacabana Beach",
    categories: ["beach", "waterfront"],
    geoCoordinates: { latitude: -22.9711, longitude: -43.1822 },
    popularityScore: 0.94,
    sourceIds: { osm: "way/240512868", wikidata: "Q175086" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Rio de Janeiro, Brazil",
    locality: "Rio de Janeiro",
    countryCode: "BR",
    countryName: "Brazil",
    name: "Escadaria Selaron",
    altNames: ["Selaron Steps"],
    categories: ["landmark", "art_district"],
    geoCoordinates: { latitude: -22.9156, longitude: -43.1792 },
    popularityScore: 0.88,
    sourceIds: { osm: "way/298353728", wikidata: "Q2631014" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Jaipur, India",
    locality: "Jaipur",
    countryCode: "IN",
    countryName: "India",
    name: "Hawa Mahal",
    categories: ["palace", "landmark"],
    geoCoordinates: { latitude: 26.9239, longitude: 75.8267 },
    popularityScore: 0.96,
    sourceIds: { osm: "way/53642268", wikidata: "Q467724" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Jaipur, India",
    locality: "Jaipur",
    countryCode: "IN",
    countryName: "India",
    name: "Amber Fort",
    altNames: ["Amer Fort"],
    categories: ["fort", "heritage_site"],
    geoCoordinates: { latitude: 26.9855, longitude: 75.8513 },
    popularityScore: 0.95,
    sourceIds: { osm: "way/49825870", wikidata: "Q498713" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Jaipur, India",
    locality: "Jaipur",
    countryCode: "IN",
    countryName: "India",
    name: "Jal Mahal",
    categories: ["palace", "waterfront"],
    geoCoordinates: { latitude: 26.9536, longitude: 75.8478 },
    popularityScore: 0.87,
    sourceIds: { osm: "way/77857380", wikidata: "Q1276141" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Jaipur, India",
    locality: "Jaipur",
    countryCode: "IN",
    countryName: "India",
    name: "City Palace Jaipur",
    categories: ["palace", "museum"],
    geoCoordinates: { latitude: 26.9255, longitude: 75.8236 },
    popularityScore: 0.9,
    sourceIds: { osm: "way/49450412", wikidata: "Q575528" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Petra, Jordan",
    locality: "Petra",
    countryCode: "JO",
    countryName: "Jordan",
    name: "Al-Khazneh",
    altNames: ["The Treasury"],
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: 30.3285, longitude: 35.4444 },
    popularityScore: 1,
    sourceIds: { osm: "node/346364542", wikidata: "Q202905" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Petra, Jordan",
    locality: "Petra",
    countryCode: "JO",
    countryName: "Jordan",
    name: "Ad Deir",
    altNames: ["The Monastery"],
    categories: ["landmark", "heritage_site"],
    geoCoordinates: { latitude: 30.3435, longitude: 35.4370 },
    popularityScore: 0.93,
    sourceIds: { osm: "node/391312082", wikidata: "Q320420" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Petra, Jordan",
    locality: "Petra",
    countryCode: "JO",
    countryName: "Jordan",
    name: "Siq",
    categories: ["landmark", "viewpoint"],
    geoCoordinates: { latitude: 30.3240, longitude: 35.4513 },
    popularityScore: 0.9,
    sourceIds: { osm: "way/26393276", wikidata: "Q751063" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
  {
    destination: "Petra, Jordan",
    locality: "Petra",
    countryCode: "JO",
    countryName: "Jordan",
    name: "High Place of Sacrifice",
    categories: ["viewpoint", "heritage_site"],
    geoCoordinates: { latitude: 30.3265, longitude: 35.4476 },
    popularityScore: 0.84,
    sourceIds: { osm: "node/346364684", wikidata: "Q1916980" },
    sourceProvenance: ["OpenStreetMap", "Wikidata"],
  },
];
